#
# -*- coding: utf-8 -*-
# Copyright 2019 Red Hat
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the resource
#   module builder playbook.
#
# Do not edit this file manually.
#
# Changes to this file will be over written
#   by the resource module builder.
#
# Changes should be made in the model used to
#   generate this file or in the resource module
#   builder template.
#
#############################################

"""
The arg spec for the nxos_acls module
"""


class AclsArgs(object):  # pylint: disable=R0903
    """The arg spec for the nxos_acls module
    """

    def __init__(self, **kwargs):
        pass

    argument_spec = {'config': {'elements': 'dict',
            'options': {'entries': {'elements': 'dict',
                                    'options': {'action': {'type': 'str'},
                                                'additional_parameters': {'type': 'str'},
                                                'destination': {'mutually_exclusive': [['address',
                                                                                        'addrgroup',
                                                                                        'any',
                                                                                        'prefix'],
                                                                                       ['wildcard_bits',
                                                                                        'addrgroup',
                                                                                        'any',
                                                                                        'prefix']],
                                                                'options': {'address': {'type': 'str'},
                                                                            'addrgroup': {'type': 'str'},
                                                                            'any': {'type': 'bool'},
                                                                            'port_protocol': {'mutually_exclusive': [['eq',
                                                                                                                      'lt',
                                                                                                                      'neq',
                                                                                                                      'portgroup',
                                                                                                                      'range'],
                                                                                                                     ['eq',
                                                                                                                      'gt',
                                                                                                                      'neq',
                                                                                                                      'portgroup',
                                                                                                                      'range']],
                                                                                              'options': {'eq': {'type': 'str'},
                                                                                                          'gt': {'type': 'str'},
                                                                                                          'lt': {'type': 'str'},
                                                                                                          'neq': {'type': 'str'},
                                                                                                          'portgroup': {'type': 'str'},
                                                                                                          'range': {'options': {'end': {'type': 'str'},
                                                                                                                                'start': {'type': 'str'}},
                                                                                                                    'type': 'dict'}},
                                                                                              'type': 'dict'},
                                                                            'prefix': {'type': 'str'},
                                                                            'wildcard_bits': {'type': 'str'}},
                                                                'required_together': [['address',
                                                                                       'wildcard_bits']],
                                                                'type': 'dict'},
                                                'log': {'type': 'bool'},
                                                'match': {'options': {'ack': {'type': 'bool'},
                                                                      'dscp': {'type': 'str'},
                                                                      'established': {'type': 'bool'},
                                                                      'fin': {'type': 'bool'},
                                                                      'http_method': {'type': 'str'},
                                                                      'packet_length': {'mutually_exclusive': [['eq',
                                                                                                                'lt',
                                                                                                                'neq',
                                                                                                                'range'],
                                                                                                               ['eq',
                                                                                                                'gt',
                                                                                                                'neq',
                                                                                                                'range']],
                                                                                        'options': {'eq': {'type': 'int'},
                                                                                                    'gt': {'type': 'int'},
                                                                                                    'lt': {'type': 'int'},
                                                                                                    'neq': {'type': 'int'},
                                                                                                    'range': {'options': {'end': {'type': 'int'},
                                                                                                                          'start': {'type': 'int'}},
                                                                                                              'type': 'dict'}},
                                                                                        'type': 'dict'},
                                                                      'precedence': {'type': 'str'},
                                                                      'psh': {'type': 'bool'},
                                                                      'rst': {'type': 'bool'},
                                                                      'syn': {'type': 'bool'},
                                                                      'ttl': {'type': 'int'},
                                                                      'udf': {'elements': 'dict',
                                                                              'options': {'mask': {'type': 'str'},
                                                                                          'name': {'type': 'str'},
                                                                                          'value': {'type': 'str'}},
                                                                              'type': 'list'},
                                                                      'urg': {'type': 'bool'},
                                                                      'vlan': {'type': 'str'}},
                                                          'type': 'dict'},
                                                'protocol': {'type': 'str'},
                                                'remark': {'type': 'str'},
                                                'sequence': {'required': True,
                                                             'type': 'int'},
                                                'source': {'mutually_exclusive': [['address',
                                                                                   'addrgroup',
                                                                                   'any',
                                                                                   'prefix'],
                                                                                  ['wildcard_bits',
                                                                                   'addrgroup',
                                                                                   'any',
                                                                                   'prefix']],
                                                           'options': {'address': {'type': 'str'},
                                                                       'addrgroup': {'type': 'str'},
                                                                       'any': {'type': 'bool'},
                                                                       'port_protocol': {'mutually_exclusive': [['eq',
                                                                                                                 'lt',
                                                                                                                 'neq',
                                                                                                                 'portgroup',
                                                                                                                 'range'],
                                                                                                                ['eq',
                                                                                                                 'gt',
                                                                                                                 'neq',
                                                                                                                 'portgroup',
                                                                                                                 'range']],
                                                                                         'options': {'eq': {'type': 'str'},
                                                                                                     'gt': {'type': 'str'},
                                                                                                     'lt': {'type': 'str'},
                                                                                                     'neq': {'type': 'str'},
                                                                                                     'portgroup': {'type': 'str'},
                                                                                                     'range': {'options': {'end': {'type': 'str'},
                                                                                                                           'start': {'type': 'str'}},
                                                                                                               'type': 'dict'}},
                                                                                         'type': 'dict'},
                                                                       'prefix': {'type': 'str'},
                                                                       'wildcard_bits': {'type': 'str'}},
                                                           'required_together': [['address',
                                                                                  'wildcard_bits']],
                                                           'type': 'dict'}},
                                    'required_together': [['action',
                                                           'protocol',
                                                           'source',
                                                           'destination']],
                                    'type': 'list'},
                        'name': {'type': 'str'}},
            'type': 'list'},
 'state': {'choices': ['deleted',
                       'gathered',
                       'merged',
                       'overridden',
                       'rendered',
                       'replaced'],
           'default': 'merged',
           'type': 'str'}}  # pylint: disable=C0301
