#
# -*- coding: utf-8 -*-
# Copyright 2019 Red Hat
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the resource
#   module builder playbook.
#
# Do not edit this file manually.
#
# Changes to this file will be over written
#   by the resource module builder.
#
# Changes should be made in the model used to
#   generate this file or in the resource module
#   builder template.
#
#############################################

"""
The arg spec for the nxos_snmp module
"""


class SnmpArgs(object):  # pylint: disable=R0903
    """The arg spec for the nxos_snmp module
    """

    def __init__(self, **kwargs):
        pass

    argument_spec = {'config': {'options': {'aaa_user': {'options': {'cache_timeout': {'type': 'int'}},
                                     'type': 'dict'},
                        'communities': {'elements': 'dict',
                                        'mutually_exclusive': [['acl',
                                                                'ipv4acl'],
                                                               ['acl',
                                                                'ipv6acl']],
                                        'options': {'acl': {'type': 'str'},
                                                    'community': {'type': 'str'},
                                                    'group': {'type': 'str'},
                                                    'ipv4acl': {'type': 'str'},
                                                    'ipv6acl': {'type': 'str'}},
                                        'type': 'list'},
                        'contact': {'type': 'str'},
                        'enable': {'type': 'bool'},
                        'engine_id': {'options': {'local': {'type': 'str'}},
                                      'type': 'dict'},
                        'global_enforce_priv': {'type': 'bool'},
                        'hosts': {'elements': 'dict',
                                  'options': {'community': {'type': 'str'},
                                              'host': {'type': 'str'},
                                              'message_type': {'choices': ['informs',
                                                                           'traps'],
                                                               'type': 'str'},
                                              'security_level': {'choices': ['auth',
                                                                             'priv'],
                                                                 'type': 'str'},
                                              'source_interface': {'type': 'str'},
                                              'udp_port': {'type': 'int'},
                                              'version': {'type': 'str'},
                                              'vrf': {'options': {'filter': {'elements': 'str',
                                                                             'type': 'list'},
                                                                  'use': {'type': 'str'}},
                                                      'type': 'dict'}},
                                  'type': 'list'},
                        'location': {'type': 'str'},
                        'packetsize': {'type': 'int'},
                        'source_interface': {'options': {'informs': {'type': 'str'},
                                                         'traps': {'type': 'str'}},
                                             'type': 'dict'},
                        'traps': {'elements': 'dict',
                                  'options': {'names': {'elements': 'dict',
                                                        'options': {'name': {'type': 'str'},
                                                                    'negate': {'type': 'bool'}},
                                                        'type': 'list'},
                                              'type': {'type': 'str'}},
                                  'type': 'list'},
                        'users': {'elements': 'dict',
                                  'options': {'aes_128': {'type': 'bool'},
                                              'algorithm': {'choices': ['md5',
                                                                        'sha'],
                                                            'type': 'str'},
                                              'enforce_priv': {'type': 'bool'},
                                              'engine_id': {'type': 'str'},
                                              'groups': {'elements': 'str',
                                                         'type': 'list'},
                                              'ipv4acl': {'type': 'str'},
                                              'ipv6acl': {'type': 'str'},
                                              'localized_key': {'type': 'bool'},
                                              'password': {'type': 'str'},
                                              'privacy_password': {'type': 'str'},
                                              'username': {'required': True,
                                                           'type': 'str'}},
                                  'type': 'list'}},
            'type': 'dict'},
 'state': {'choices': ['merged',
                       'replaced',
                       'overridden',
                       'deleted',
                       'template'],
           'default': 'merged',
           'type': 'str'}}  # pylint: disable=C0301
